version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - .env.test

  web:
    build: .
    command: >
      sh -c "
      echo '⏳ Waiting for DB...' &&
      sleep 10 &&
      pytest tests/ --cov=core --cov-report=xml
      "
    env_file:
      - .env.test
    depends_on:
      - db