# Generated by Django 5.2 on 2026-05-14 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='chat.chatroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Activity',
                'verbose_name_plural': 'Chat Activities',
                'db_table': 'chat_activity',
            },
        ),
    ]
